steps:
# Copy configuration bucket.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app',
  'deploy' ,
  'app.yaml',
  '--bucket=${_BUCKET}',
  '--project=${_PROJECT_ID}',
  '--promote',
  '--stop-previous-version',
  '--quiet'
  ]
